cloudify-cosmo/cloudify-agent

- appveyor.yml
appveyor environment change caused package install under wrong python (miniconda 64bit)
> CFY-2649 fix failing test_local_agent_from_package test

- dev-requirements.txt
- test-requirements.txt
moved dsl parser from dev-requirements to test-requirements
> CFY-3583-remove-dsl-parser-from-agent-requirements

- cloudify_agent/installer/__init__.py
- cloudify_agent/shell/commands/configure.py
- cloudify_agent/tests/installer/test_operations.py
- setup.py
the previous _fix_virtualenv method left the scripts broken when the
virtualenv path was longer than about 256 bytes (can't run a program
with a shebang longer than 256).
virtualenv's own method of making venvs relocatable does almost
what we want (uses a /usr/bin/env shebang and a "activate this"
snippet), but is too strict (only works on not-yet-moved virtualenvs,
while agent packages have already been moved).
This changeset adapts virtualenv's method, turning off the checking.
(while very long virtualenv names might be rare/nonexistent in practice,
some system tests have a test_id long enough to break because of this;
this fixes cosmo_tester.test_suites.test_blueprints.puppet_plugin_test
.PuppetPluginStandaloneTest.test_puppet_standalone_with_resource)
> CFY-5111 use virtualenv's method of fixing shebangs

- cloudify_agent/api/utils.py
The old one would remove trailing padding `=`'s, which caused problems for flask-security
> CFY-5948 Replace base64 encode function

- cloudify_agent/api/utils.py
- cloudify_agent/tests/api/test_utils.py
If username or password for RabbitMQ contained any characters that
need to be escaped when present in URL, bootstrap procedure failed
when trying to start management worker.
This commit prevents such characters from making it into final broker
URL by properly quoting them.
> Properly quote RabbitMQ username and password

- cloudify_agent/installer/runners/fabric_runner.py
- cloudify_agent/tests/installer/runners/test_fabric_runner.py
In this PR, fabric configuration is updated to raise exceptions instead of calling `sys.exit(1)` when ssh authentication fails.
This is useful because a more apropriate messsage is now written to logs:
> 2016-11-01 20:21:20.129  CFY <cloudify-nodecellar-example> [host_exm847.create] Task rescheduled 'cloudify_agent.installer.operations.create' -> Needed to prompt for a connection or sudo password (host: 172.20.0.3), but abort-on-prompts was set to True [retry 1]
Before this PR, the error message was just `1` which is what was passed to the `SystemExit` exception.
> CFY-5877 Raise exceptions on ssh prompts

- cloudify_agent/resources/pm/nssm/nssm.conf.template
In this PR, some quotes that where missing around the service command have been added.
The changes have been successfully tested by runnnig the hello world example against a windows VM.
> CFY-6380 Add quotes that were missing in service command

- cloudify_agent/resources/pm/nssm/nssm.conf.template
In this PR, the cloudify agent service configuration is updated to set the display name and description. The name is still the same, so this doesn't affect any command, just the representation of the service in the GUI:
The description is kind of a placeholder, so any suggestion for a better description would be welcome.
> CFY 6382. Set service display name and description in Windows

- cloudify_agent/resources/pm/nssm/nssm.conf.template
In this PR, the cloudify agent service configuration is updated to set the display name and description. The name is still the same, so this doesn't affect any command, just the representation of the service in the GUI:
Port of: #208
> CFY 6382. Set service display name and description (port to 4.0)

- cloudify_agent/api/utils.py
- setup.py
In this PR, the [`apddirs`](https://pypi.python.org/pypi/appdirs/1.4.0) library is used to get a directory to store cloudify agent data across different platforms.
In the test with windows, instead of using `C:\Users\Admin\.cfy-agent`, it now uses `C:\Users\cloudbase-init\AppData\Local\Cloudify\cloudify-agent`
> CFY 6381. Update storage directory default

- cloudify_agent/api/utils.py
- setup.py
In this PR, the [`apddirs`](https://pypi.python.org/pypi/appdirs/1.4.2) library is used to get a directory to store cloudify agent data across different platforms.
In the test with windows, instead of using `C:\Users\Admin\.cfy-agent`, it now uses `C:\ProgramData\Cloudify\cloudify-agent\`.
> CFY 6381. Update storage directory default (port to 4.0)

- cloudify_agent/installer/config/attributes.py
- cloudify_agent/installer/config/configuration.py
- cloudify_agent/tests/test_operations.py
- setup.py
- test-requirements.txt
In this PR, the `service_name` property is added to the agent.
The change has been verified using the hello world example templates for openstack in both windows and linux. The values tested have been strings without spaces because from what I've seen service names follow these patterns:
- Linux: `service_name`
- Windows: `ServiceName`
so I'd recommend using them.
Note: given that `cloudify_manager['name']` is used in multiple places, the easiest and less risky way to apply the change is to set `cloudify_manager['name']` to `cloudify_manager['service_name']` rather than changing every occurrence of `name` to use `service_name` in the code.
> CFY 6382. Add service_name property

- cloudify_agent/installer/config/attributes.py
- cloudify_agent/installer/config/configuration.py
In this PR, the `service_name` property is added to the agent.
Port of: #219
> CFY 6382. Add service_name property (port to 4.0)

- cloudify_agent/installer/__init__.py
In this PR, quotes around `cfy-agent` path are added to take into account the case in which it contains spaces.
> CFY-6380 Add quotes around cfy-agent path

- circle.yml
When I updated `circle.yml` recently, I introduced a problem as a result of joining multiple commands in the same case statement. The problem is that if a command before the last one fails, then its error code is lost and CircleCI reports the tests as passed.
In this PR, the problem is fixed by adding `set -e` when multiple commands are executed. This needs to be added multiple times because CircleCI uses a different shell each time.
> Make sure errors are reported in CircleCI

- cloudify_agent/installer/__init__.py
In this PR, quotes around cfy-agent path are added to take into account the case in which it contains spaces.
Port of: #225
> CFY-6380 Add quotes around cfy-agent path (port to 4.0)

- circle.yml
- tox.ini
In this PR, the `install_command` used in tox configuration files is updated to include the `-U` flag. This should take care of the case in which a cloudify package has been cached in a tox virtualenv, but it's been updated later by pushing a new change to github using the same version number.
Related: cloudify-cosmo/cloudify-manager#761
> Always upgrade packages in tox virtualenvs

- appveyor.yml
This is because another test run happens with the contents of the PR
after being merged which is what is more interesting to know.
> Skip running tests for a branch when PR is open

- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/runners/winrm_runner.py
- test-requirements.txt
In this PR, a couple of quotes related to the installation of the cloudify agent on windows using winrm have been added to support paths with spaces.
> CFY 6380. Add missing quotes for winrm scenario

- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/runners/winrm_runner.py
In this PR, a couple of quotes related to the installation of the cloudify agent on windows using winrm have been added to support paths with spaces.
> CFY 6380. Add missing quotes for winrm scenario (port to 4.0)

- cloudify_agent/installer/__init__.py
This is a small refactoring to quote the cfy agent path both on windows and linux.
Related: #234
> Quote cfy agent path

- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/config/attributes.py
- cloudify_agent/operations.py
- cloudify_agent/shell/commands/installer.py
- cloudify_agent/tests/__init__.py
- cloudify_agent/tests/test_operations.py
- dev-requirements.txt
The new agents upgrade process is as follows:
* Upon issue of a `cfy agents install` command, a new
`install_agent.py` script is rendered, with a REST token and the SSL
certificate inside it.
* It is then moved to a special location inside the file server
(/resources/cloudify_agent), with a fresh UUID prepended to it.
* The request is sent to the celery client on the agent machine,
and processed by the worker thread there (this is as it was before)
* The old agent downloads the script, which holds all the info
necessary to update the SSL certificate, and then proceed to
download and install the new agent package, as before
> CFY-6577 Fix agents upgrade after snapshot restore

- cloudify_agent/installer/runners/winrm_runner.py
This is because the `-Force` flag is not recognized by cmd, so the
command needs to be executed through powershell to avoid getting errors
if the command is executed multiple times.
> Run mkdir through powershell

- cloudify_agent/shell/commands/installer.py
- cloudify_agent/tests/__init__.py
- cloudify_agent/tests/api/pm/__init__.py
- cloudify_agent/tests/api/pm/test_base.py
- cloudify_agent/tests/api/test_factory.py
- cloudify_agent/tests/api/test_utils.py
- cloudify_agent/tests/installer/script/test_init_script.py
- cloudify_agent/tests/installer/test_operations.py
- cloudify_agent/tests/shell/__init__.py
- cloudify_agent/tests/shell/commands/__init__.py
- cloudify_agent/tests/shell/commands/test_install_local.py
- cloudify_agent/tests/test_operations.py
- tox.ini
As the `install_agent.py` script runs on the old mgmtworker env, it
might not have the new `local_rest_cert_path` function, so we pass it
directly in the script
> CFY-6577 Fix `cfy agents install` for 3.4.2 snapshots

- setup.py
In version 2.1.3 paramiko introduced pynacl as a dependency. We'd like
to void that.
> CFY-6990 Explicitly set paramiko's version, to avoid pynacl trouble

- cloudify_agent/installer/operations.py
- cloudify_agent/installer/script.py
- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/resources/script/windows-download.ps1.template
In this PR, the agent installation script functionality is updated to add an indirection step, that is, instead of generating a script that performs the agent installation, that script gets generated is together with another script that downloads the first one and executes it.
> Agent install link

- cloudify_agent/installer/script.py
- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/tests/resources/blueprints/install-new-agent/install-new-agent-blueprint.yaml
* CFY-7124 Fix userdata script running sudo command without tty
* CFY-7124 Allow users to pass an `install_with_sudo` extra param
By default, this shouldn't be relevant for users, but it might
become handy for provided installs (and tests)
> CFY-7124 Fix userdata script running sudo command without tty (#286)

- cloudify_agent/installer/script.py
- cloudify_agent/operations.py
This is instead of inferring whether sudo is needed from the install
method.
The only 3 cases that use the `init_script` method are:
1. Regular userdata - in which case sudo is not needed
2. Agents upgrade - in which case the install method would be
irrelevant in any case, and passing an argument would be necessary
3. System tests/other provided scenarios - in which case it is
somewhat more flexible (and up to the user) to require providing
the argument
> CFY-7124 Make the `install_with_sudo` param mandatory

- cloudify_agent/installer/runners/winrm_runner.py
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/tests/installer/runners/test_winrm_runner.py
In this PR, the code that sends the agent installation script to a windows server is updated to split the script into chunks.
The reason to split the script is that to the script is included as part of a powershell command, so its size is restricted by the maximum command line length supported in windows to avoid getting a command line too long error.
Related: #289
> CFY-7142. Fix command line too long (port to 4.2)

- cloudify_agent/installer/runners/fabric_runner.py
In this PR, a try/finally block is used to make sure that the installation script is always removed.
During manual tests, the script was already being deleted, so no changes have been required as in the winrm case.
Related:  #291
> CFY-7107. Delete agent installation script (ssh)

- cloudify_agent/installer/runners/winrm_runner.py
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/tests/installer/runners/test_winrm_runner.py
In this PR, the code that sends the agent installation script to a windows server is updated to split the script into chunks.
The reason to split the script is that to the script is included as part of a powershell command, so its size is restricted by the maximum command line length supported in windows to avoid getting a command line too long error.
> CFY-7142. Fix command line too long

- cloudify_agent/installer/script.py
- cloudify_agent/resources/script/linux.sh.template
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/tests/installer/script/test_install_script.py
In this PR, the linux and windows agent installation script templates are updated
to separate clearly the implementation of the install, configure and start steps.
This way, it will be easier to render only the parts that are needed.
For now, the default is to render all three parts. The logic to decide when to render
them or not will be added in a future PR.
I've tested both linux and windows scenarios and the agents were still successfully
installed. Hence, this refactoring doesn't affect the functionality as it should be.
> CFY-7105. Refactor agent installation script templates

- cloudify_agent/installer/script.py
- cloudify_agent/resources/script/linux.sh.template
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/tests/installer/script/test_install_script.py
In this PR, the linux and windows agent installation script templates are updated
to separate clearly the implementation of the install, configure and start steps.
This way, it will be easier to render only the parts that are needed.
For now, the default is to render all three parts. The logic to decide when to render
them or not will be added in a future PR.
Related: #295
> CFY-7105. Refactor agent installation script templates (port to 4.2)

- cloudify_agent/installer/script.py
- cloudify_agent/operations.py
This is instead of inferring whether sudo is needed from the install
method.
The only 3 cases that use the `init_script` method are:
1. Regular userdata - in which case sudo is not needed
2. Agents upgrade - in which case the install method would be
irrelevant in any case, and passing an argument would be necessary
3. System tests/other provided scenarios - in which case it is
somewhat more flexible (and up to the user) to require providing
the argument
> CFY-7124 Make the `install_with_sudo` param mandatory (#288)

- cloudify_agent/installer/script.py
- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/resources/script/linux.sh.template
- cloudify_agent/resources/script/windows-download.ps1.template
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/tests/__init__.py
In the cases where the download script is used, avoid having the
certificate in the install script, instead using the same path to
which it was downloaded in the download script
> CFY-7168 Add cert in download script for userdata/agent upgrade

- cloudify_agent/installer/config/agent_config.py
Before the refactor, we used to run .retry() and not continue trying
to use the runner. Now we need to make sure this behaviour is kept:
we set .retry(), and then we need to make sure no further attempts
to use the runner are done. So, in that case, we simply `return` from
the caller function.
> On an error is raised while creating a runner, retry and don't continue

- cloudify_agent/app.py
Turns out it's not required at all. Only one process will run this
code at a time anyway.
> CFY-7246 Remove the lockfile around updating settings

- cloudify_agent/api/plugins/installer.py
We cannot allow the CommandExecutionError to bubble up, because then
the operation will be (hopelessly) retried. Instead, we should re-throw
it as an PluginInstallationError so that the framework above us changes
it into an NonRecoverableError and stops trying.
We also log the whole output, because for the common failures, the
reason can be seen there easily (eg. not having gcc when trying to
install the openstack plugin from source).
> CFY-7345 Make sure a `pip install` error is rethrown

- cloudify_agent/app.py
- cloudify_agent/shell/commands/configure.py
This is not a real solution of the problem we have with how the rest
server fetches events/logs, but this is a quick and easy fix for the
problem (which is - 2 identical messages written in the same millisecond
to the DB)
> CFY-7444 Prevent behavior where the same message is written twice to DB

- cloudify_agent/operations.py
Otherwise, the new agent will be installed pointing to the old cluster
> CFY-7564 Agents upgrade: pass new cluster

- tox.ini
This is because by default Circle CI will fail on Python 2.6 due to 
the dev-requirements depending on plugins common, which now
utilizes a relatively advanced setuptools capability (`find_packages`)
which is not available in the default version of setuptools that comes
with the image
> Upgrade setuptools when running tests

- cloudify_agent/installer/script.py
The windows init/install scripts don't require a user
> CFY-7729 Only pass a user when not working with windows over userdata

- appveyor.yml
- setup.py
- tox.ini
* Using `pip.exe install -U pip` tries to overwrite pip.exe while it's obviously in use,
so on windows, this fails with a AccessDenied error.
* We need pip 9.0.1 installed because that's what has the API that the plugin
installer expects
* We can't use `python -m pip` on python 2.6, must use straight `pip` instead.
Fortunately, we only need 2.6 on linux.
> On windows, don't use `pip.exe` to upgrade pip

- cloudify_agent/api/plugins/installer.py
Because the new runners only accept lists
> Pass the pip freeze command as a list

- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/operations.py
* agent_config.local in agent upgrade as well
* ..and copy the local field from the old agent
* Just default local to False
* ...but still set it
* add a comment
* Add install_method too
* Pre-4.2 agents: use rest_host for script path
> agent_config.local in agent upgrade as well (#367)

- cloudify_agent/api/pm/base.py
- cloudify_agent/api/utils.py
- cloudify_agent/tests/__init__.py
- cloudify_agent/tests/api/pm/test_detach.py
- cloudify_agent/tests/api/pm/test_initd.py
That might be thrown when the agent didn't create the exchange yet.
In this case, it's obviously very much NOT alive
> is_agent_alive: handle ChannelClosed

- cloudify_agent/api/plugins/installer.py
- cloudify_agent/operations.py
Need a way to uninstall only the source plugins, to be used in
delete-deployment-environment
> Plugins uninstall: make uninstalling managed plugins optional

- .circleci/config.yml
- Setting a specific tox version for supporting the use of tox in current circleci python image for python 26
> CY-471 : Fixing python 26 unit tests run

- cloudify_agent/api/plugins/installer.py
This allows to run eg. `pip install -r req.txt /pluginpath`
instead of `pip install /pluginpath -r req.txt`. Therefore, the
things passed in plugin's install_arguments will be installed first,
and declaring a requirements.txt this way will become possible
> PluginInstaller: put args before the package path

- cloudify_agent/resources/pm/systemd/systemd.template
Instead of assuming it's the group named the same as the user
> systemctl: use the user's primary group

- cloudify_agent/resources/script/linux.sh.template
Downloading the agent package into a temporary created *directory* (not a file; see below), and then deleting that directory at the end.
Downloading into a temporary-generated *file* would require the `wget`/`curl` command to overwrite that file. This is straightforward with `curl` but I trust it less with `wget` (see: https://serverfault.com/questions/171369/how-to-allow-wget-to-overwrite-files).
> CY-747: download agent package into temporary directory

- cloudify_agent/api/plugins/installer.py
- cloudify_agent/tests/api/plugins/test_installer.py
Previously it was done by the pip library when we used it directly
> CY-687 Properly convert windows paths to file:// URIs

- setup.py
- test-requirements.txt
- also reverting virtualenv version change due that they had dropped support for python 2.6
> build failure - fixing cryptography version in test-requirements.txt

- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/resources/script/linux.sh.template
When run in CI, this causes mountains of useless text showing the entire download process.
> Avoid showing progress bar when using wget

- cloudify_agent/api/plugins/installer.py
Adds a log message for the last stage of the sourced plugin installation, where the installation directory is moved to a different one; making it easier to see where the agent installed it's plugins.
> CY-1060 Add more info for plugin source installations

- packaging/docker-compose.yaml
To be reverted when we have working RHEL base images again
> Temporarily stop building RHEL agents

- cloudify_agent/shell/commands/daemons.py
Make sure that paths like "~ubuntu/cloudify/ssl/cert.pem" are resolved.
Otherwise, click.Path tries the literal "~ubuntu" and finds that it
doesn't exist
> Path args to cfy-agent: expanduser

- cloudify_agent/worker.py
When setting an envvar with data that is coming from json (which
is unicode) we need to make sure that the string which goes
into the environ is bytes, or otherwise we'll be having trouble
starting subprocesses with `Popen(.., env=os.environ.copy())`.
Linux subprocess/os.environ copes with values that are unicode but
only contain ascii, however windows doesn't.
> CY-1985 Make sure envvars are bytes

- cloudify_agent/resources/pm/systemd/systemd.template
The agent is expected to be restarted on connection loss, and so
systemd must be configured to keep restarting it until it actually
connects again
> CY-1960 systemd agent: add RestartSec=2

- cloudify_agent/api/pm/base.py
That's not compatible with 2+3.
And anyway, that's in logger.debug, so it wouldn't be emitted.
> Daemon status: avoid calling str()

- .circleci/config.yml
- setup.py
It's only needed for the mgmtworker
> CY-2534 Make the fabric installation optional

- setup.py
Agent never uses pyyaml directly. (common does)
> Drop pyyaml dependency

- cloudify_agent/tests/installer/runners/test_fabric_runner.py
- cloudify_agent/tests/test_operations.py
- cloudify_agent/tests/utils.py
- test-requirements.txt
However, in the unittests, we still need them, because the unittests do
run workflows.
So this means the dev-reqs.txt, which is what is used to build the agent,
installs cloudify-common, but test-reqs.txt, which is used to run the test,
uses cloudify-common[dispatcher].
The tests then build the agent WITHOUT dispatcher, from dev-reqs.txt,
and use that in their "end-to-end" tests that install an agent
> requirements.txt: install common without the optionals

- cloudify_agent/api/plugins/installer.py
- cloudify_agent/api/pm/base.py
- cloudify_agent/api/utils.py
- cloudify_agent/operations.py
- cloudify_agent/tests/__init__.py
- cloudify_agent/tests/api/plugins/test_installer.py
- cloudify_agent/tests/api/pm/__init__.py
Instead of installing a subset of libraries into a prefix, using the agent
venv as the constraints: install the plugin into a new virtualenv.
To actually run operations from that plugin, you now have to call
`python -m cloudify.dispatch` in the plugin venv, not in the agent venv.
(so in principle, it could be a different python version)
That means the usage is different, and the change in calling is done
inside cloudify-cosmo/cloudify-common#468
Unfortunately we still need _some_ insanity in it, because of course
to run operations, the plugin needs cloudify-common, for the dispatch
infrastructure.
> CY-2658 Make a virtualenv when installing plugins

- packaging/docker-files/centos_6/Dockerfile
- packaging/docker-files/centos_7/Dockerfile
- packaging/docker-files/rhel_6/Dockerfile
- packaging/docker-files/rhel_7/Dockerfile
- packaging/docker-files/ubuntu_14_04/Dockerfile
- packaging/docker-files/ubuntu_16_04/Dockerfile
- packaging/docker-files/ubuntu_18_04/Dockerfile
- packaging/docker-files/ubuntu_20_04/Dockerfile
We still keep the git links in reqs.txt, so git must be present
on the build images
> Packaging: install git on the build images [ci skip]

- dev-requirements.txt
- packaging/docker-files/centos_6/Dockerfile
- packaging/docker-files/centos_7/Dockerfile
- packaging/docker-files/rhel_6/Dockerfile
- packaging/docker-files/rhel_7/Dockerfile
- packaging/docker-files/ubuntu_14_04/Dockerfile
- packaging/docker-files/ubuntu_16_04/Dockerfile
- packaging/docker-files/ubuntu_18_04/Dockerfile
- packaging/docker-files/ubuntu_20_04/Dockerfile
- packaging/stub_packages/cloudify-dsl-parser/setup.py
- packaging/stub_packages/cloudify-plugins-common/setup.py
- packaging/stub_packages/cloudify-rest-client/setup.py
- packaging/stub_packages/cloudify-script-plugin/setup.py
Now is the time to do it. Thank you and goodbye, stubs.
We used to have empty stub packages like "cloudify-plugins-common" that were only
there so that plugins who declare that they require "cloudify-plugins-common" were
able to be installed.
Now that we make separate virtualenvs, if a plugin wants cloudify-plugins-common,
it will actually install it from the wagon instead.
But there's no need to install it, because that's a 3-year-old-deprecated package.
> CY-2743 Stop shipping stub packages

- packaging/windows/main.tf
Apparently AWS' version of cloudbase-init is a bit fragile and just won't run the winrm commands in a <powershell> tag.
> Move win builder winrm config to script tag

- cloudify_agent/api/plugins/installer.py
- cloudify_agent/tests/api/plugins/test_installer.py
Plugins are now installed on-demand, on-the-fly, on-first-use.
There's no need for them to be replicated to anything.
There's no need to bookkeep the "installing" state of them.
> CY-3015 Plugin installer: drop the replication-related bits

- cloudify_agent/resources/script/linux.sh.template
If we're already running as the user that is supposed to install
the agent, no need to use `su`
> linux install script: don't use `su` if not required

- cloudify_agent/api/plugins/installer.py
For consistency, create the id file for all plugins.
I intend to use this file as a "this is actually a plugin directory"
marker ("...a fully installed plugin, at that")
> Plugin installation: also create the id file for source plugins

- cloudify_agent/api/pm/detach.py
- cloudify_agent/resources/pm/detach/detach.template
- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/resources/script/linux.sh.template
This allows the detach agent to run with absolutely no sudo/su calls.
This allows easy usage in the sanity-check, with no required setup on the manager.
> Avoid using sudo/su in download.sh and in detach agent

- cloudify_agent/installer/config/agent_config.py
detach agents dont need sudo, so they dont need to disable anything
> When using detach agent, don't use disable-requiretty

- packaging/windows/main.tf
Otherwise, passing an empty dev branch results in the upload arg being used as the branch name.
> Quote windows packaging args

- cloudify_agent/api/plugins/installer.py
Instead of get_python_path, which will _attempt_ to reconstruct sys.executable
when passed VIRTUALENV (and will fail on embedded pythons), just use
sys.executable directly, which is always going to be correct
> plugin installer: use sys.executable directly

- cloudify_agent/resources/script/windows.ps1.template
Because we create the base dir when we add the SSL cert, and the
current test then means we don't actually install the agent code.
> Check scripts dir exists to see if agent installed

- cloudify_agent/worker.py
Retry agent connection in-process instead of relying on
external restarts (eg. systemd).
See cloudify-cosmo/cloudify-manager#2318 for an in-depth explanation
> CY-3237 Agent: retry connection

- cloudify_agent/resources/pm/nssm/nssm.conf.template
- cloudify_agent/resources/script/windows-download.ps1.template
- cloudify_agent/resources/script/windows.ps1.template
Write-Output seems to result in swallowed logs when a failure occurs- possibly when a failure
occurs in the same block. Write-Host seems to reliably be captured by our logs.
> Use Write-Host on windows for better logging

- cloudify_agent/resources/pm/nssm/nssm.conf.template
There's an extra space in there so that we don't end up with the log level being set to, e.g. '7CFY_EXEC_TEMP=c:\\users\\admini~1\\appdata\\local\\temp'
> CY-3339 Don't set invalid log level in nssm conf

- diamond_agent/tasks.py
- setup.py
This is to stop them crashing out when trying to perform day 2 operations.
> CY-3477 Add stub for old blueprints with diamond

- cloudify_agent/worker.py
See commits. Hide the retry traceback, and also only display the traceback if it's there.
> CY-3584 Hide useless tracebacks

- cloudify_agent/shell/commands/cfy.py
Without this change, sanity-check's uninstall (and presumably other similar operations)
fails due to the 'locale' call returning an empty string.
> Do not fail due to no locale on sanity uninstall

- cloudify_agent/tests/api/plugins/test_installer.py
- cloudify_agent/tests/utils.py
- packaging/windows/packaging/create_install_wizard.iss
- packaging/windows/win_agent_builder.ps1
- test-requirements.txt
The main purpose of this change is to fix the issue for building the windows agent and also make the tests passed on branch 5.1.0-build by adding all the required CI files so that it can be run on jenkins. Moreover, the name of the windows agent for GA release is not going to have a `ga` suffix`
> RD-804 Re-release windows agent 5.1.0

- packaging/windows/packaging/create_install_wizard.iss
Otherwise they will try to install to the same location and the sky will fall down.
> Use a different app name for different win agents

- cloudify_agent/api/factory.py
Specifically, 4.6 seems to create some that don't have the process_management key.
However, this will also cope with any other old/broken agent configs.
> RD-928 Cope with malformed agent json

- cloudify_agent/api/factory.py
Specifically, 4.6 seems to create some that don't have the process_management key.
However, this will also cope with any other old/broken agent configs.
> RD-928 Cope with malformed agent json (#732)

- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/resources/script/linux.sh.template
This PR added to handle a special case about cento8 generation name when it comes to download that agent on target host machine since the code-name sometimes empty and equal to the code name of Centos 7 'core'. so the generation of the name should have suffix name called `8` instead of `core` so that we can fetch the correct generated agent located inside the file server
> RD-862 Allow to build Centos 8

- cloudify_agent/resources/script/linux.sh.template
It used to be lowercased before, but #724 lost the `.lower()` call, which
makes agents impossible to be downloaded and installed.
> linux.sh.template: also lowercase the codename

- cloudify_agent/installer/config/agent_config.py
This PR created to fix issue with download agent from file server where it distro name should be  first converted  to lower case so the correct agent should be picked up correctly
> Convert distro name to lower before generate package url for agent

- dev-requirements.txt
Since the agent for RHEL6/Python 2.6 uses its own dev-requirements.txt
we may try bumping the version to the most recent one for all other
builds.
> RD-1287 Pika version upgrade

- dev-requirements.txt
We add a constraint on the cloudify common so that we can install the suitable pika version for python version where we always used/install pika == 0.11.2 for python >=2.6 or python < 2.7.9 and since dev-req.txt already have reference to common so no need to pin/install the pika again on the dev-req.txt
> RD-1345 Use pika 0.11.2 for python version < 2.7.9

- cloudify_agent/api/pm/base.py
- cloudify_agent/installer/operations.py
When doing a deployment update on a pre-existing host, we try to reuse
the agent name, which can cause failures if a snapshot restore has been
run and the old manager removed, so we will work around that by trying
to remove the agent if an install fails.
> RD-1707 Handle deployment update failure

- cloudify_agent/api/pm/base.py
- cloudify_agent/api/pm/detach.py
Why would we always enable it?
> RD-2625 If cron_respawn is false, don't enable it

- cloudify_agent/worker.py
> RD-2966 Use os.pathsep for creating PATH

- cloudify_agent/tests/test_dispatch.py
- cloudify_agent/worker.py
Skip updating operation state, if the plugin is using an old version
of cloudify-common, because then, the subprocess's dispatch.py
is going to do it.
And we can't do it twice, because if we set an operation to started,
and it was already started before, then we consider that a resume.
> RD-2976 Don't update operation state for old plugins

- cloudify_agent/api/utils.py
- cloudify_agent/resources/script/linux-download.sh.template
- cloudify_agent/resources/script/linux.sh.template
Without that patch, curl (7.29.0) didn't properly recognize IPv6
localhost (`::1`) address when combined with a port number (`:53333`).
> WDR-77 Fix the way curl handles the `::1` address

- setup.py
It's the last version which supports Python 2.7.
This way we drop anyjson dependency (which is broken as of 2021-09-07).
> Upgrade celery to version 4.4.7

- setup.py
It's the last version which supports Python 2.7.
This way we drop anyjson dependency (which is broken as of 2021-09-07).
> RD-3124 Upgrade celery to version 4.4.7

- packaging/windows/win_agent_builder.ps1
These are now out of path because nssm starts with the embedded python
directory in path (as that's where it runs), but not the scripts subdir.
Previously this worked because python.exe was in the scripts subdir.
> RD-3307 Set symlinks for windows ctx and cfy-agent

- cloudify_agent/worker.py
Handler isn't used here ever since #800
> RD-3407 Remove unused attribute

- cloudify_agent/worker.py
- setup.py
Obviously, if we set it in the environ, and never set it back, that's
no bueno.
Funnily, we don't even need it here, because in the current process,
it's already set on ctx; and we pass it to child processes explicitly,
when creating _their_ env.
> RD-3946 Don't leak bypass_maintenance between executions

- setup.py
pin jinja2 version to 2.13 for two reasons:
1. to fix vulnerability: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28493
2. to match with cloudify-common pinned jinja2 version
> pin jinja2 version

- cloudify_agent/tests/resources/blueprints/agent-from-package/local-agent-blueprint.yaml
- cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint-windows.yaml
- cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint.yaml
- jenkins/bp/ec2-cfy-agent-tests-blueprint.yaml
- jenkins/build-pod-windows.yaml
A known issue in Jenkins causes windows JNLP containers to take a few seconds to connect.
Adding the args to retry the connection after a few seconds seem to stabilize it.
Also using an older types.yaml in the blueprint to have it working with the 1_3 dsl as the manager+cli used is prior to 6.4.0
> RD-5553 Windows jnlp agent connectivity ci

- cloudify_agent/operations.py
In cloudify-cosmo/cloudify-common#1055 I've made it so that
gat_daemon_name returns None if the envvar is missing. Let's abort
then, so that we don't attempt to read None.json
> RD-4923 Error out on empty daemon name

- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/tests/api/plugins/test_installer.py
- cloudify_agent/tests/installer/config/test_configuration.py
- cloudify_agent/tests/utils.py
- jenkins/Jenkinsfile
- test-requirements.txt
- download our 3.10 build and extract that
- only clone the single branch we need
- better `jq` usage :)
- clean up test-reqs.txt (newer pytest version required for py3.10)
> CI: run tests on 3.10

- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/operations.py
In CM 7.0 we moved to manylinux agents. The distro and distro_codename fields no longer exist, replaced by an architecture field
> RD-6529 Handle distro->architecture field change in 7.0

- cloudify_agent/resources/script/linux.sh.template
Essentially, for `detach`, like in the sanity-check, we want to avoid sudo at all costs. Basedir had better already be set.
> RD-6658 linux.sh: specialcase `detach` agents even more

- cloudify_agent/shell/main.py
For compat with existing operations that use it (e.g. delete), it must be stored
> RD-6985 Agent setup: also store agent_dir in runtime properties

- cloudify_agent/api/pm/base.py
- cloudify_agent/shell/main.py
It needs to be stored when we're running as the agent user. It was called in configure, which is called as root, which lead to the conf file being owned by root.
> RD-7028 agent install: store broker_conf in `cfy-agent setup`

- appveyor.yml
- cloudify_agent/shell/main.py
- jenkins/Jenkinsfile
- jenkins/bp/ec2-cfy-agent-tests-blueprint.yaml
Using a global location (/tmp/resources) by default a bad idea because:
- it'll be accessible by other agents
- the agent user doesn't necessarily have write permissions there
> RD-7005 Put the resources/ dir under agent dir

- cloudify_agent/resources/script/windows.ps1.template
It is required, and linux passes it in too. It was just missed in the windows one.
> RD-7005 Windows install script: add --name to `daemons` commands

- cloudify_agent/resources/script/windows.ps1.template
I'm not sure why StartAgent has this "check if already exists", because linux doesn't have it.
Anyway, let's still have it.
So `daemons list` shows the daemon to exist, if `cfy-agent setup` has been called. Therefore, we must run `daemons create` right next to `setup`. Otherwise, we end up calling `setup`, but never actually `daemons create`.
> RD-7005 windows.ps1: create daemon when setting up agent

- packaging/windows/win_agent_builder.ps1
We can't use venv directly, so let's use virtualenv, and pretend that it's venv. Heh.
> RD-205 windows package: provide a stub "venv"

- cloudify_agent/api/utils.py
- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/installer/linux.py
- cloudify_agent/installer/script.py
- cloudify_agent/installer/windows.py
- cloudify_agent/operations.py
- cloudify_agent/resources/script/linux.sh.template
- cloudify_agent/resources/script/windows.ps1.template
- cloudify_agent/shell/main.py
- cloudify_agent/tests/installer/config/test_configuration.py
- cloudify_agent/tests/test_operations.py
- keep the configured basedir, don't revert to the default
- separately pass in node-instance-id, which only defaults to the name
> RD-7005 Agent upgrade directory fixups

- cloudify_agent/operations.py
- cloudify_agent/resources/script/windows.ps1.template
This operation renders the operation context in-line so that it can be sent to the old agent's rabbitmq;  we better include the rest port in it too, like all other operations do. Otherwise, the remote agent tries to look up the port in envvars, and that might be missing (will be missing, for new agents).
Also, use rest_host from our current ctx. It always must be the current manager, and anyway - we include the rest_token for the current manager.
> RND-262 Upgrade operation: put rest_port in the context

- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/runners/winrm_runner.py
- cloudify_agent/tests/installer/test_utils.py
This ports #892 to 7.0.0
* RND-293 Fixup windows cfy-agent path
This now mirrors the actual install_dir
* fix the imports
the utils were re-imported, let's just import from the actual source instead
> RND-293 Fixup windows cfy-agent path

- cloudify_agent/installer/__init__.py
- cloudify_agent/installer/config/agent_config.py
- cloudify_agent/tests/installer/config/test_configuration.py
This isn't used anymore, because shell.py/main, just downloads the cert using the restclient
> RND-386 Remove unused BROKER_SSL_CERT_PATH envvar

- cloudify_agent/installer/operations.py
- cloudify_agent/installer/script.py
- cloudify_agent/operations.py
Instead of direct filesystem access, upload the scripts (and then delete) to the fileserver using ctx methods.
> RND-389 Agent install scripts: use the fileserver

- cloudify_agent/operations.py
When upgrading, just ignore the old package_url, remove it, and then it'll be defaulted (in the script) to the newest on-manager package.
Otherwise, upgrading 6.x agents, will attempt to fetch e.g. redhat-maipo-agent.tgz, which doesn't exist anymore (now it's just manylinux agents)
> RD-7004 agent upgrade: reset package_url

- cloudify_agent/operations.py
This is necessary following https://github.com/cloudify-cosmo/cloudify-agent/pull/899,
since the manager_ip and cert will be empty during the upgrade to the new agents (7+)
> Remove early return for empty IP and cert
