cloudify-cosmo/cloudify-agent

cloudify_agent/installer/config/attributes.py
cloudify_agent/installer/config/configuration.py
cloudify_agent/installer/operations.py
cloudify_agent/tests/installer/config/test_configuration.py
system_tests/manager/test_agent_installer.py
system_tests/resources/userdata-agent-blueprint/plugins/mock-plugin/mock_plugin/tasks.py
system_tests/resources/userdata-agent-blueprint/userdata-agent-blueprint.yaml

remote_execution related issues

CFY-2649 Fix userdata based test and fix non

---

cloudify_agent/api/utils.py
cloudify_agent/operations.py
cloudify_agent/tests/__init__.py
cloudify_agent/tests/api/pm/__init__.py
cloudify_agent/tests/resources/blueprints/install-new-agent/install-new-agent-blueprint.yaml
cloudify_agent/tests/resources/blueprints/install-new-agent/scripts/copy_agent_data.py
cloudify_agent/tests/shell/commands/test_install_local.py
cloudify_agent/tests/test_operations.py

* CFY-4381 Certificates support in install_new_agents
* CFY-4382 Sanity checks for agents
This the replacement for #75

CFY-4381 and CFY-4382

---

cloudify_agent/api/utils.py
cloudify_agent/operations.py
cloudify_agent/tests/__init__.py
cloudify_agent/tests/api/pm/__init__.py
cloudify_agent/tests/resources/blueprints/install-new-agent/install-new-agent-blueprint.yaml
cloudify_agent/tests/resources/blueprints/install-new-agent/scripts/copy_agent_data.py
cloudify_agent/tests/shell/commands/test_install_local.py
cloudify_agent/tests/test_operations.py

(direct copy of #80)
* CFY-4381 Certificates support in install_new_agents
* CFY-4382 Sanity checks for agents

CFY-4381 and CFY-4382 (master)

---

cloudify_agent/app.py

We will only use them in case of clustered agents

Don't always use AMQP heartbeats

---

appveyor.yml
tox.ini

In this PR, the appveyor configuration is updated to:
- Use software already present in the build environment  (erlang)
- Cache downloads (chocolatey, rabbitmq and tox environments)
- Remove unnecessary/duplicated code
From the test runs that I've seen, these changes make the execution finish around 4-5 minutes earlier.

Appveyor improvements

---

cloudify_agent/resources/pm/nssm/nssm.conf.template

In this PR, some quotes that where missing around the service command have been added.
Port of: #206

CFY-6380 Add quotes that were missing in service command (port to 4.0)

---

cloudify_agent/operations.py

Otherwise, the code on the other side won't be able to deal with it

CFY-7086 Send agent config as dict instead of object

---

cloudify_agent/installer/config/agent_config.py
cloudify_agent/installer/script.py
cloudify_agent/operations.py
cloudify_agent/resources/script/linux-download.sh.template
cloudify_agent/tests/resources/blueprints/install-new-agent/install-new-agent-blueprint.yaml
cloudify_agent/tests/test_operations.py

Now only validate old AMQP before agent upgrade and new AMQP after
agent upgrade

CFY-7064 Use new agent install framework in agent upgrade

---

cloudify_agent/installer/runners/winrm_runner.py

In this PR, the agent installation script is successfully deleted from the remote windows machine after installation or failure during the script execution.

CFY-7107. Delete agent installation script (winrm)

---

cloudify_agent/api/plugins/installer.py
cloudify_agent/tests/api/plugins/test_installer.py

CY-203: provide subprocess.Popen args as a list

---

cloudify_agent/api/plugins/installer.py
setup.py

* CY-215 Pass pip args as a list to wagon.install
* Bump wagon version to 0.6.3

CY-215 Pass pip args as a list to wagon.install (#354)

---

cloudify_agent/tests/resources/winpackage/create.iss

Seriously WHY do we have two files

Move the virtualenv args to tests create.iss as well

---

.circleci/config.yml
cloudify_agent/worker.py

We want to keep retrying for a connection forever in the agent worker

Worker: no connect_timeout

---

appveyor.yml
cloudify_agent/api/factory.py
cloudify_agent/api/pm/nssm.py
cloudify_agent/resources/pm/detach/detach.template
cloudify_agent/resources/pm/initd/initd.template
cloudify_agent/resources/pm/nssm/nssm.conf.template
cloudify_agent/tests/api/pm/__init__.py
cloudify_agent/tests/api/test_factory.py

The same agent can be installed multiple time in an idempotent
manner. The config file will be overwritten.

CY-148 Agents install: overwrite the agent config file

---

dev-requirements.txt

CY-409 Remove the stubs packages from dev-requirements

---

.circleci/config.yml
setup.py

Following cloudify common change

CY-471 : Updating jinja2 package

---

.circleci/config.yml

- So not needing to install the package

codecov: switch to bash coverage uploader

---

cloudify_agent/installer/operations.py
cloudify_agent/installer/runners/winrm_runner.py
cloudify_agent/resources/script/windows-download.ps1.template
cloudify_agent/resources/script/windows.ps1.template

Including fixing logging as well (see my comments in the code itself below).

CY-1051: Properly handle Windows agent installation problems

---

dev-requirements.txt
test-requirements.txt

- Updating dev req to master, because the CI should always use the latest versions
- Removing diamond due to removing support

Dev-requirements: updating dev req

---

cloudify_agent/installer/config/agent_config.py
cloudify_agent/installer/config/installer_config.py
cloudify_agent/installer/runners/fabric_runner.py
cloudify_agent/installer/runners/winrm_runner.py
cloudify_agent/installer/script.py
cloudify_agent/resources/script/linux-download.sh.template
cloudify_agent/resources/script/linux.sh.template
cloudify_agent/tests/api/plugins/test_installer.py

* Use agent's tempdir for creating tmp dirs in the runners
* Use agent tempdirs in the init/download scripts
* Flake
* Add `if`s in the jinja templates

CY-1013 Use agent's tmpdir for the installation scripts (#486)

---

cloudify_agent/worker.py

* Change the HookConsumer to inherit from CloudifyOperationConsumer
* Use the handle_task of CloudifyOperationConsumer, so it will run the hook in
subprocess with env that contains the plugin

CY-1041 Refactor the actionable events (hooks)

---

.circleci/config.yml
cloudify_agent/tests/__init__.py
cloudify_agent/tests/api/plugins/test_installer.py
cloudify_agent/tests/installer/script/test_install_script.py
cloudify_agent/tests/installer/test_operations.py
cloudify_agent/tests/shell/commands/test_install_local.py
cloudify_agent/tests/test_operations.py
cloudify_agent/tests/utils.py
test-requirements.txt

Unittest fixes

---

cloudify_agent/api/plugins/installer.py
cloudify_agent/tests/api/plugins/test_installer.py
dev-requirements.txt

and wait for Syncthing to sync files on all Managers if cluser

CY-1244 Plugins install: replace local lock mechanism with DB lock,

---

cloudify_agent/api/plugins/installer.py

installing central_deployment_agent plugins

Wait for Syncthing and update plugin name only when

---

cloudify_agent/worker.py

This is the other side of cloudify-cosmo/cloudify-common#337

Send no response when a task is kill-cancelled

---

cloudify_agent/installer/__init__.py
cloudify_agent/installer/config/agent_config.py
cloudify_agent/operations.py
cloudify_agent/tests/installer/config/__init__.py
cloudify_agent/tests/installer/config/test_configuration.py
cloudify_agent/tests/installer/script/test_install_script.py
cloudify_agent/tests/installer/test_operations.py
cloudify_agent/tests/shell/commands/test_install_local.py
cloudify_agent/tests/test_operations.py

See commit messages
Instead of using utils.get_tenant in places, use ctx.tenant

Set tenant in agent_config

---

.circleci/config.yml

- adding apt-get update for updating the links for the os packages

build fix:

---

appveyor.yml
cloudify_agent/tests/resources/winpackage/create.iss
packaging/windows/packaging/create_install_wizard.iss

CY-2011: Cap tox version in appveyor.yml + drop diamond plugin installation

---

test-requirements.txt

test-reqs: pin testtools version

---

cloudify_agent/installer/runners/fabric_runner.py

this is for when using the key from a secret, not from filename

Fabric runner: pass private key correctly

---

cloudify_agent/tests/__init__.py
cloudify_agent/tests/resources/blueprints/agent-from-package/scripts/create-package.py
packaging/linux/packager.yaml
packaging/local.yaml

For compatibility with agent-packager 5.x

agent-packager configs: use .ini

---

packaging/windows/main.tf

It's not powershell, but if it's not in the powershell section it seems to be silently ignored.

Run netsh in powershell section

---

cloudify_agent/api/plugins/installer.py
cloudify_agent/operations.py
cloudify_agent/tests/api/plugins/test_installer.py
cloudify_agent/tests/api/pm/conftest.py
cloudify_agent/tests/api/pm/daemons.py
cloudify_agent/tests/api/pm/shared.py
cloudify_agent/tests/conftest.py
cloudify_agent/tests/plugins.py
cloudify_agent/tests/utils.py
cloudify_agent/worker.py

And update plugin installation state.

CY-3094 Service task to force-install plugins

---

cloudify_agent/api/plugins/installer.py
cloudify_agent/operations.py

package_name is not always present after all

Plugin installer: fallback to plugin.name

---

cloudify_agent/installer/operations.py

Remove that todo! Delete the agent queues and exchange.
If we fail to do that, because the agent dict is malformed - oh well,
we can't do it then.

CY-3216 Delete agent AMQP resources when deleting the agent

---

packaging/docker-files/centos_6/Dockerfile
packaging/docker-files/centos_7/Dockerfile
packaging/docker-files/rhel_6/Dockerfile
packaging/docker-files/rhel_7/Dockerfile

Yum + overlayfs don't play nice together. I don't fully understand
why. The internet suggested several solutions, none of which work
by themselves.
This seems to be enough to make it work.
I'm not gonna waste any more time trying to understand it.

Build dockerfiles: cope with docker's overlayfs

---

cloudify_agent/operations.py

It might be the case that the plugin was already deleted, because
we're uninstalling it from the whole system.
In this case, no need to try and update its state, it's gone.
Just ignore the 404 then.

uninstall_plugins: don't break on plugin missing

---

setup.py

We don't import pip anymore, so no need for this

CY-3325 Don't pin to specific pip version

---

cloudify_agent/resources/pm/nssm/nssm.conf.template

I missed the {%- and -%} in the previous commit.

CY-3339 Don't eat necessary space in nssm.conf

---

cloudify_agent/api/utils.py
cloudify_agent/operations.py

It now goes into the plugin installer proper.

CY-3534 Move updating plugin state to common

---

cloudify_agent/VERSION
cloudify_agent/tests/resources/blueprints/agent-from-package/local-agent-blueprint.yaml
cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint-windows.yaml
cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint.yaml
cloudify_agent/tests/resources/blueprints/install-new-agent/install-new-agent-blueprint.yaml
cloudify_agent/tests/resources/plugins/mock-plugin-modified/setup.py
cloudify_agent/tests/resources/plugins/mock-plugin-with-requirements/setup.py
cloudify_agent/tests/resources/plugins/mock-plugin/setup.py
setup.py

This reverts commit 09343f6614f7d9f4a45fe7fdb72a7bf77a0b583c.

Revert "Bump version"

---

jenkins/Jenkinsfile

Fix bug with multiple EC2 termination failure

Fix bug with multiple EC2 termination failure

---

jenkins/Jenkinsfile

...instead of relying on autodetection in the agent-packager

RD-977 Agent build: declare distro name explicitly

---

cloudify_agent/installer/config/agent_config.py
cloudify_agent/installer/script.py
cloudify_agent/resources/script/linux-download.sh.template
cloudify_agent/resources/script/linux.sh.template

There has to be a better way. The scripts eventually will require
massive refactoring.

Skip the cfyagent group `sg` calls for detach agents

---

jenkins/Jenkinsfile
test-requirements.txt

RD-1341 check build stability, and fix python2 pytests

Rd 1341 check stability

---

test-requirements.txt

Push py2 test fix to 5.2.0-build

---

jenkins/build-pod.yaml

RD-1559 fix QoS for pod to fix stability issues of pipeline

RD-1559 fix QoS for pod

---

jenkins/Jenkinsfile

py2.7. url changed, updated jenkinsfile accordingly

fix py2.7 url

---

jenkins/Jenkinsfile
jenkins/bp/ec2-blueprint.yaml
jenkins/build-pod.yaml

add catchError to windows stage, increase volume size for ec2 on bp, increase resources for py36

RD-2489 Enhance pipeline (#789)

---

cloudify_agent/worker.py

Updating the operation from outside now. It feels a bit nicer to wrap
the whole subprocess in the state handling
And in the future this is one we'll be able to optimize better.

RD-514 Move updating operation update to OperationHandler

---

cloudify_agent/worker.py

6.2.0.dev1 should _not_ be considered lower than 6.2.0

RD-2976 cloudify-common version check: also drop suffixes

---

jenkins/Jenkinsfile
setup.py

RD-3124 Upgrade celery to version 4.4.7 (#815) (#816)

---

cloudify_agent/api/utils.py
setup.py

cloudify-cosmo/cloudify-common#1046 moves this

RD-4921 move is_agent_alive

---

cloudify_agent/shell/commands/configure.py

Most of the venv doesn't contain paths, but THIS file does. Well. Let's
rewrite it still.
This allows the user to activate the venv by hand in a shell. No real
reason for them to do so, but they might.

RD-5248 agent install: fixup virtualenv activate script

---

cloudify_agent/tests/conftest.py
cloudify_agent/tests/installer/test_operations.py
cloudify_agent/tests/resources/blueprints/agent-from-package/local-agent-blueprint.yaml
cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint-windows.yaml
cloudify_agent/tests/resources/blueprints/install-agent/test-install-agent-blueprint.yaml
cloudify_agent/tests/shell/commands/test_install_local.py
jenkins/Jenkinsfile
jenkins/bp/ec2-cfy-agent-tests-blueprint.yaml
jenkins/build-pod.yaml

this ports #846 and #848 to 6.4.1, and also does some version pins so that CI can run

6.4.1: CI fixups

---

jenkins/Jenkinsfile
jenkins/bp/ec2-cfy-agent-tests-blueprint.yaml

Infra blueprint: use 6.3.0 types

---

cloudify_agent/worker.py

This is the other part of cloudify-cosmo/cloudify-manager#4041

RD-6586 Allow parametrizing rest_port

---

packaging/windows/win_agent_builder.ps1

See the comment. I don't currently have a better idea.

RD-7005 Windows builder: download venv

---

packaging/windows/win_agent_builder.ps1

We can't use venv directly, so let's use virtualenv, and pretend that it's venv. Heh.

RD-205 windows package: provide a stub "venv"

---

jenkins/Jenkinsfile

...rabbitmq just doesn't seem to work. I give up.

CI: don't run rabbitmq tests on windows

---

packaging/windows/packaging/create_install_wizard.iss

This mirrors the changes in #889

RD-7005 create_install_wizard.iss: update paths

---

cloudify_agent/installer/__init__.py
cloudify_agent/installer/runners/winrm_runner.py
cloudify_agent/tests/installer/test_utils.py

This now mirrors the actual install_dir

RND-293 Fixup windows cfy-agent path

---

cloudify_agent/installer/script.py

install/upgrade: on windows, add an extension to the script

---

requirements.txt

Change patch version to be aligned with the cloudify-common.

Update requirements.txt aiohttp
